# Generated by Django 6.1.1 on 2026-09-29 08:35

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Admission number, staff ID or phone number. Unique within the school.', max_length=150, validators=[django.core.validators.RegexValidator(message='Usernames may contain letters, digits and the characters . @ + - _ /', regex='^[\\w.@+/-]+$')], verbose_name='username')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('principal', 'Principal'), ('deputy_principal', 'Deputy Principal'), ('finance_admin', 'Finance Admin'), ('teacher', 'Teacher'), ('parent', 'Parent/Guardian')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('must_change_password', models.BooleanField(default=True, help_text='When set, the user must choose a new password before doing anything else.')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='schools.school')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['school__name', 'username'],
                'indexes': [models.Index(fields=['school', 'role'], name='user_school_role_idx'), models.Index(fields=['school', 'is_active'], name='user_school_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), models.F('school'), name='uniq_user_school_username_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('username'), condition=models.Q(('school__isnull', True)), name='uniq_user_platform_username_ci'), models.CheckConstraint(condition=models.Q(models.Q(('role', 'super_admin'), ('school__isnull', True)), models.Q(models.Q(('role', 'super_admin'), _negated=True), ('school__isnull', False)), _connector='OR'), name='user_role_school_consistent')],
            },
        ),
    ]
